export const PRODUCTS_LIST_REQUEST = "PRODUCTS_GET_REQUEST";
export const PRODUCTS_LIST_SUCCESS = "PRODUCTS_GET_SUCCESS";
export const PRODUCTS_LIST_FAIL = "PRODUCTS_GET_FAIL";
export const GET_SERVER_ERRORS = "GET_SERVER_ERRORS";
export const FILTER_PRODUCTS_BY_SIZE = "FILTER_PRODUCTS_BY_SIZE";
export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE";